import React from 'react';

import NavBar from '../components/layout/navbar';
import Hero from '../components/features/water-solutions/hero';
import TreatmentDetail from '../components/features/water-solutions/treatment-detail';
import ChemicalShowcase from '../components/features/water-solutions/chemical-showcase';
import ChemicalSplit from '../components/features/water-solutions/chemical-split';
import KnowledgeCenter from '../components/features/about/knowledge-center';
import Cta from '../components/features/water-solutions/cta';
import Footer from '../components/common/footer';

import { paths } from '../lib/data';

const crumbs = [
  { path: paths.home, label: 'Home' },
  { path: paths.chemicals, label: 'Our Chemicals' },
  { path: paths.fluidMonitoring, label: 'Fluid Condition Monitoring' },
];

const FluidConditionMonitoringPage: React.FC = () => {
  return (
    <React.Fragment>
      <NavBar />

      <Hero
        title="Fluid Condition Monitoring"
        crumbs={crumbs}
        image="/fluid-monitoring/hero.svg"
        imageAlt="Industrial chemical manufacturing facility at twilight"
        description="Our Fluid Condition Monitoring services provide accurate, data-driven insights into the health and performance of critical industrial fluids and equipment. Through advanced laboratory analysis and expert interpretation, we help organizations monitor lubricant, fuel, coolant, transformer oil, and process fluid conditions to detect potential issues before they lead to costly failures. Our proactive approach enables predictive maintenance, extends equipment life, reduces downtime, and improves overall operational reliability across a wide range of industries."
      />

      <TreatmentDetail
        title="Lubricating Oil Analysis"
        description="Evaluates the condition of lubricants and the health of the equipment they protect."
        image="/fluid-monitoring/lubricating.svg"
        imageAlt="Technical blue liquid in glass laboratory flask"
        cardTitle="Evaluates the condition of lubricants and the health of the equipment they protect."
        items={[
          'Viscosity analysis',
          'Oxidation and nitration testing',
          'Total Acid Number (TAN)',
          'Total Base Number (TBN)',
          'Additive depletion monitoring',
          'Contamination assessment',
        ]}
        mutedCardTitle
      />

      <ChemicalShowcase
        legend="Wear Debris Analysis"
        title="Wear Debris Analysis"
        description="Identifies and quantifies wear particles generated by machinery components."
        items={['Ferrous wear analysis', 'Particle counting', 'Spectrometric analysis', 'Ferrography', 'Root cause identification of component wear']}
        image="/fluid-monitoring/wear-debris.svg"
        imageAlt="Chemist in a high-tech laboratory using advanced analytical equipment"
      />

      <ChemicalSplit
        legend="Contamination Monitoring"
        title="Contamination Monitoring"
        description="Detects contaminants that can degrade fluid performance and damage equipment."
        items={['Corrosion inhibitors', 'Scale inhibitors', 'Biocides', 'Dispersants', 'Anti-foaming agents']}
        images={[{ src: '/fluid-monitoring/contamination.svg', alt: 'Contamination monitoring in an industrial fluid system' }]}
        imagePosition="left"
      />

      <ChemicalShowcase
        legend="Hydraulic Fluid Monitoring"
        title="Hydraulic Fluid Monitoring"
        description="Ensures hydraulic systems operate efficiently and reliably."
        items={['Cleanliness level measurement (ISO cleanliness codes)', 'Water content analysis', 'Viscosity monitoring', 'Particle contamination analysis']}
        image="/fluid-monitoring/hydraulic.svg"
        imageAlt="Hydraulic fluid sample analysis in a laboratory"
      />

      <TreatmentDetail
        title="Transformer Oil Analysis"
        description="Assesses the condition of insulating oils in electrical transformers."
        image="/fluid-monitoring/transformer.svg"
        imageAlt="Insulating oil sample in a laboratory flask"
        cardTitle="Assesses the condition of insulating oils in electrical transformers."
        items={['Dissolved Gas Analysis (DGA)', 'Moisture content', 'Dielectric strength testing', 'Acidity testing', 'Furan analysis']}
        mutedCardTitle
      />

      <ChemicalSplit
        legend="Fuel Analysis"
        title="Fuel Analysis"
        description="Monitors fuel quality and suitability for use."
        items={['Water and sediment testing', 'Fuel degradation assessment', 'Sulfur content analysis', 'Microbial contamination monitoring', 'Fuel stability testing']}
        images={[{ src: '/fluid-monitoring/fuel.svg', alt: 'Fuel quality testing equipment' }]}
        imagePosition="right"
      />

      <ChemicalSplit
        legend="Coolant Analysis"
        title="Coolant Analysis"
        description="Evaluates cooling system performance and protection."
        items={['Glycol concentration', 'pH measurement', 'Corrosion inhibitor levels', 'Contamination assessment']}
        images={[{ src: '/fluid-monitoring/coolant.svg', alt: 'Coolant sample analysis' }]}
        imagePosition="left"
      />

      <ChemicalShowcase
        legend="Process Fluid Monitoring"
        title="Process Fluid Monitoring"
        description="Tracks the condition of fluids used in industrial processes."
        items={['Chemical composition analysis', 'Contamination monitoring', 'Concentration control', 'Performance evaluation']}
        image="/fluid-monitoring/process-fluid.svg"
        imageAlt="Process fluid monitoring in an industrial facility"
      />

      <ChemicalSplit
        legend="Laboratory Testing and Diagnostics"
        title="Laboratory Testing and Diagnostics"
        description="Provides detailed insights into fluid and equipment condition."
        items={['Elemental analysis', 'Infrared spectroscopy', 'Particle characterization', 'Water determination', 'Advanced diagnostic testing']}
        images={[{ src: '/fluid-monitoring/laboratory.svg', alt: 'Advanced laboratory diagnostic equipment' }]}
        imagePosition="left"
      />

      <KnowledgeCenter />

      <Cta />

      <Footer />
    </React.Fragment>
  );
};

export default FluidConditionMonitoringPage;
