import type { CareerRole } from './types';

export const ALL_ROLES: CareerRole[] = [
  {
    id: '1',
    title: 'Technical Services Engineer',
    location: 'Lagos',
    jobType: 'Full-time',
    level: 'Mid Level',
    department: 'Technical Services',
    postedDate: '12 Jun 2026',
    endDate: '30 Jul 2026',
    featured: true,
    status: 'OPEN',
    applications: 42,
    appTrend: 'up',
  },
  {
    id: '2',
    title: 'Laboratory Analyst',
    location: 'Port Harcourt',
    jobType: 'Full-time',
    level: 'Entry Level',
    department: 'Laboratory Services',
    postedDate: '10 Jun 2026',
    endDate: '25 Jul 2026',
    featured: false,
    status: 'OPEN',
    applications: 28,
    appTrend: 'down',
  },
  {
    id: '3',
    title: 'QHSE Officer',
    location: 'Lagos',
    jobType: 'Full-time',
    level: 'Mid Level',
    department: 'QHSE',
    postedDate: '04 Jun 2026',
    endDate: '20 Jul 2026',
    featured: true,
    status: 'DRAFT',
    applications: 0,
    appTrend: null,
  },
  {
    id: '4',
    title: 'Graduate Trainee Programme',
    location: 'Nigeria',
    jobType: 'Trainee',
    level: 'Entry Level',
    department: 'Graduate Trainee',
    postedDate: '01 Jun 2026',
    endDate: '15 Aug 2026',
    featured: true,
    status: 'OPEN',
    applications: 126,
    appTrend: 'up',
  },
  {
    id: '5',
    title: 'Supply Chain Coordinator',
    location: 'Lagos',
    jobType: 'Full-time',
    level: 'Mid Level',
    department: 'Supply Chain & Logistics',
    postedDate: '25 May 2026',
    endDate: '30 Jun 2026',
    featured: false,
    status: 'CLOSED',
    applications: 64,
    appTrend: null,
  },
  {
    id: '6',
    title: 'Business Development Manager',
    location: 'Lagos',
    jobType: 'Full-time',
    level: 'Senior Level',
    department: 'Commercial',
    postedDate: '18 May 2026',
    endDate: '18 Jul 2026',
    featured: false,
    status: 'OPEN',
    applications: 33,
    appTrend: 'up',
  },
  {
    id: '7',
    title: 'HSE Supervisor',
    location: 'Abuja',
    jobType: 'Full-time',
    level: 'Mid Level',
    department: 'QHSE',
    postedDate: '14 May 2026',
    endDate: '14 Jul 2026',
    featured: false,
    status: 'DRAFT',
    applications: 0,
    appTrend: null,
  },
  {
    id: '8',
    title: 'Procurement Officer',
    location: 'Lagos',
    jobType: 'Full-time',
    level: 'Entry Level',
    department: 'Supply Chain & Logistics',
    postedDate: '10 May 2026',
    endDate: '10 Jul 2026',
    featured: false,
    status: 'OPEN',
    applications: 57,
    appTrend: 'up',
  },
];
